### ISSUE TITLE
env KUBERNETES_VERIFY_TLS not respected by code?

### ISSUE THREAD

**Issue by goern** [thoth-station/graph-refresh-job#15]
```
---> Running application from Python script (app.py) ...
INFO:thoth.graph_refresh_job:Version of thoth-storages: '0.0.19'
Traceback (most recent call last):
  File "app.py", line 136, in <module>
    main()
  File "app.py", line 132, in main
    graph_refresh()
  File "app.py", line 125, in graph_refresh
    pod_id = run_solver(solver, packages)
  File "app.py", line 107, in run_solver
    return _do_run_pod(template)
  File "app.py", line 54, in _do_run_pod
    verify=KUBERNETES_VERIFY_TLS
  File "/opt/app-root/lib/python3.6/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/opt/app-root/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/app-root/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/app-root/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/opt/app-root/lib/python3.6/site-packages/requests/adapters.py", line 407, in send
    self.cert_verify(conn, request.url, verify, cert)
  File "/opt/app-root/lib/python3.6/site-packages/requests/adapters.py", line 226, in cert_verify
    "invalid path: {0}".format(cert_loc))
OSError: Could not find a suitable TLS CA certificate bundle, invalid path: 0
```

**Comment by goern** [comment]
see `https://<hostname>/console/project/thoth-test-core/browse/pods/graph-refresh-1524671400-8kcdt?tab=environment`

**Comment by fridex** [comment]
Are you running the current master? This should be fixed by https://github.com/thoth-station/graph-refresh-job/commit/194c78e4c44f65a833406c1311a64f11cab134cb

**Comment by goern** [comment]
ha, was using :latest rather than :stable as it is supposed to be in TEST
