### ISSUE TITLE
gremlin server error prevents job from completing... constant restart

### ISSUE THREAD

**Issue by goern** [thoth-station/graph-refresh-job#29]
thoth.graph_refresh_job:Version v0.1.0+c66fc8647a6f6b8f5f9d03ac043b2d806760f6b7.thoth_storages-0.0.19 keeps on restarting, see https://upshift.engineering.redhat.com/console/project/thoth-test-core/browse/pods/graph-refresh-1525413900-l4f5l?tab=logs

```

---> Running application from Python script (app.py) ...
--
  | INFO:thoth.graph_refresh_job:Version v0.1.0+c66fc8647a6f6b8f5f9d03ac043b2d806760f6b7.thoth_storages-0.0.19
  | Traceback (most recent call last):
  | File "app.py", line 164, in <module>
  | main()
  | File "app.py", line 160, in main
  | graph_refresh()
  | File "app.py", line 137, in graph_refresh
  | for package, versions in graph.retrieve_unsolved_pypi_packages().items():
  | File "/opt/app-root/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py", line 146, in retrieve_unsolved_pypi_packages
  | return asyncio.get_event_loop().run_until_complete(query)
  | File "uvloop/loop.pyx", line 1364, in uvloop.loop.Loop.run_until_complete
  | File "/opt/app-root/lib/python3.6/site-packages/aiogremlin/process/graph_traversal.py", line 56, in next
  | return await self.__anext__()
  | File "/opt/app-root/lib/python3.6/site-packages/aiogremlin/process/graph_traversal.py", line 17, in __anext__
  | self.last_traverser = await self.traversers.__anext__()
  | File "/opt/app-root/lib/python3.6/site-packages/aiogremlin/driver/resultset.py", line 66, in __anext__
  | msg = await self.one()
  | File "/opt/app-root/lib/python3.6/site-packages/aiogremlin/driver/resultset.py", line 16, in wrapper
  | "{0}: {1}".format(msg.status_code, msg.message))
  | aiogremlin.exception.GremlinServerError: 500: 500: None

```

**Comment by fridex** [comment]
This looks like an error on gremlin side - it is returning 500. I think the graph-refresh job keeps restarting correctly in this case. Close?

**Comment by fridex** [comment]
Closing this as graph-sync job now works. Feel free to reopen if the issue appears again.
