### ISSUE TITLE
retrieve_dependent_packages() missing argument 'package_name'

### ISSUE THREAD

**Issue by goern** [thoth-station/graph-refresh-job#34]
```
--> Running application from Python script (app.py) ...
INFO:thoth.graph_refresh_job:Version of thoth-storages: '0.0.19'
Traceback (most recent call last):
  File "app.py", line 136, in <module>
    main()
  File "app.py", line 132, in main
    graph_refresh()
  File "app.py", line 120, in graph_refresh
    for dependent_package, dependent_versions in graph.retrieve_dependent_packages().items():
TypeError: retrieve_dependent_packages() missing 1 required positional argument: 'package_name'
```

**Comment by fridex** [comment]
Fixed in https://github.com/thoth-station/graph-refresh-job/pull/10
