### ISSUE TITLE
send metric to pushgateway on exception

### ISSUE THREAD

**Issue by goern** [thoth-station/graph-refresh-job#83]
**Is your feature request related to a problem? Please describe.**
I would like to send some metric to the pushgateway if a exception like this raises:
```

2018-09-15 14:24:52,732 [1] CRITICAL root: Traceback (most recent call last):
--
  | File "/opt/app-root/lib/python3.6/site-packages/openshift/dynamic/client.py", line 31, in inner
  | resp = func(self, resource, *args, **kwargs)
  | File "/opt/app-root/lib/python3.6/site-packages/openshift/dynamic/client.py", line 161, in create
  | return self.request('post', path, body=body, **kwargs)
  | File "/opt/app-root/lib/python3.6/site-packages/openshift/dynamic/client.py", line 255, in request
  | _return_http_data_only=params.get('_return_http_data_only', True)
  | File "/opt/app-root/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 321, in call_api
  | _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  | File "/opt/app-root/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 155, in __call_api
  | _request_timeout=_request_timeout)
  | File "/opt/app-root/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 364, in request
  | body=body)
  | File "/opt/app-root/lib/python3.6/site-packages/kubernetes/client/rest.py", line 266, in POST
  | body=body)
  | File "/opt/app-root/lib/python3.6/site-packages/kubernetes/client/rest.py", line 222, in request
  | raise ApiException(http_resp=r)
  | kubernetes.client.rest.ApiException: (403)
  | Reason: Forbidden
  | HTTP response headers: HTTPHeaderDict({'Cache-Control': 'no-store', 'Content-Type': 'application/json', 'Date': 'Sat, 15 Sep 2018 14:24:52 GMT', 'Content-Length': '309'})
  | HTTP response body: b'{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods \\"solver-f26-8dl8m\\" is forbidden: exceeded quota: gold-quota, requested: limits.cpu=750m, used: limits.cpu=15550m, limited: limits.cpu=16","reason":"Forbidden","details":{"name":"solver-f26-8dl8m","kind":"pods"},"code":403}\n'
  | During handling of the above exception, another exception occurred:
  | Traceback (most recent call last):
  | File "app.py", line 78, in <module>
  | main()
  | File "app.py", line 74, in main
  | graph_refresh()
  | File "app.py", line 63, in graph_refresh
  | pod_id = _OPENSHIFT.run_solver(solver=solver, debug=_LOG_SOLVER, packages=packages, output=_SOLVER_OUTPUT)
  | File "/opt/app-root/lib/python3.6/site-packages/thoth/common/openshift.py", line 256, in run_solver
  | namespace=self.middletier_namespace
  | File "/opt/app-root/lib/python3.6/site-packages/openshift/dynamic/client.py", line 33, in inner
  | raise api_exception(e)
  | openshift.dynamic.exceptions.ForbiddenError: 403
  | Reason: Forbidden
  | HTTP response headers: HTTPHeaderDict({'Cache-Control': 'no-store', 'Content-Type': 'application/json', 'Date': 'Sat, 15 Sep 2018 14:24:52 GMT', 'Content-Length': '309'})
  | HTTP response body: b'{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods \\"solver-f26-8dl8m\\" is forbidden: exceeded quota: gold-quota, requested: limits.cpu=750m, used: limits.cpu=15550m, limited: limits.cpu=16","reason":"Forbidden","details":{"name":"solver-f26-8dl8m","kind":"pods"},"code":403}\n'
  | Original traceback:
  | File "/opt/app-root/lib/python3.6/site-packages/openshift/dynamic/client.py", line 31, in inner
  | resp = func(self, resource, *args, **kwargs)
  | File "/opt/app-root/lib/python3.6/site-packages/openshift/dynamic/client.py", line 161, in create
  | return self.request('post', path, body=body, **kwargs)
  | File "/opt/app-root/lib/python3.6/site-packages/openshift/dynamic/client.py", line 255, in request
  | _return_http_data_only=params.get('_return_http_data_only', True)
  | File "/opt/app-root/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 321, in call_api
  | _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  | File "/opt/app-root/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 155, in __call_api
  | _request_timeout=_request_timeout)
  | File "/opt/app-root/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 364, in request
  | body=body)
  | File "/opt/app-root/lib/python3.6/site-packages/kubernetes/client/rest.py", line 266, in POST
  | body=body)
  | File "/opt/app-root/lib/python3.6/site-packages/kubernetes/client/rest.py", line 222, in request
  | raise ApiException(http_resp=r)
```

**Describe the solution you'd like**
n/a

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by fridex** [comment]
Speaking of this maybe it will be better to set up [Sentry](https://sentry.io/) and configure logging to send exceptions there. Exceptions are something that should not occur and if we have an exception, Sentry can capture context and additional info for us so we can debug it. I'm not sure if Prometheus metrics are relevant here.

We should put this logic to one place - that is the logging configuration in common - https://github.com/thoth-station/common/blob/master/thoth/common/logging.py and make this configurable (like send info to Sentry if ``THOTH_SENTRY_DSN`` is provided).
