### ISSUE TITLE
THOTH_MIDDLETIER_NAMESPACE seems to be missing from cronjob declaration

### ISSUE THREAD

**Issue by goern** [thoth-station/graph-refresh-job#9]
```

---> Running application from Python script (app.py) ...
--
  | Traceback (most recent call last):
  | File "app.py", line 31, in <module>
  | THOTH_MIDDLETIER_NAMESPACE = os.environ['THOTH_MIDDLETIER_NAMESPACE']
  | File "/opt/app-root/lib64/python3.6/os.py", line 669, in __getitem__
  | raise KeyError(key) from None
  | KeyError: 'THOTH_MIDDLETIER_NAMESPACE'

```

**Comment by fridex** [comment]
Fixed in https://github.com/thoth-station/graph-refresh-job/pull/10
